### ISSUE TITLE
dTLS Support with PSK

### ISSUE THREAD

**Issue by zubairhamed** [zubairhamed/canopus#7]

**Comment by louisZL** [comment]
Has canopus provided dTLS security?

**Comment by zubairhamed** [comment]
Not yet. Not wanting to reinvent the wheel, i was waiting out if Golang would provide it. Using CGo with OpenSSL etc might be an option too. Interestingly enough there's some discussions on this couple of weeks back.

https://github.com/golang/go/issues/13525

I'll probably wait out a bit more on how this develops before deciding..

Z

**Comment by louisZL** [comment]
How long would they will implement the DTLS on Golang?

**Comment by jvermillard** [comment]
The last OpenSSL pre2 version support the AES-CCM8 PSK ciphersuite so a binding on OpenSSL using memory based BIO would be a trick

**Comment by zubairhamed** [comment]
Thanks for the hint. I was monkeying around with the last version of OpenSSL and CGO but it got overwhelming for me a bit there. I think i'll take another crack at this.

**Comment by andreyevsyukov** [comment]
Really curious about DTLS support in canopus too! Can we expect it the nearest future?
Thanks.

**Comment by jvermillard** [comment]
I started a binding to openssl 1.1 (which support CCM8)

https://github.com/jvermillard/nativedtls

You can use it for DTLS client using PSK only for now, I need more time to do the server code.

Should be enough to connect a canopus based client to californium or leshan. Also I tested vs tinydtls server, it's working.

**Comment by zubairhamed** [comment]
Thanks Julian, that looks great. I'll give it a go. I'm a bit over my head with crypto.

Z

**Comment by zubairhamed** [comment]
dTLS added in ad1de684b531cf11adf7df7bd4b9b4a6cfe409d0

**Comment by jvermillard** [comment]
![](https://media.giphy.com/media/mXnO9IiWWarkI/giphy.gif)
